TAGS:
  - "Rht8"
  - "busco"

ASSEMBLIES:
  - "AGS2000"
  - "Hilliard"
  
CHRS:
  - "1A"
  - "1B"
  - "1D"
  - "2A"
  - "2B"
  - "2D"
  - "3A"
  - "3B"
  - "3D"
  - "4A"
  - "4B"
  - "4D"
  - "5A"
  - "5B"
  - "5D"
  - "6A"
  - "6B"
  - "6D"
  - "7A"
  - "7B"
  - "7D"
  - "ptg"
